[1,"\u001B[31mERROR: NotFound: O sistema não pode encontrar o arquivo especificado. (os error 2): stat 'C:\\Users\\m_tai\\Documents\\repos\\prob_inf\\.Rproj.user\\17CA65A4\\pcs'\r\n"]
[1,"\r\n"]
[1,"Stack trace:\r\n"]
[1,"    at Object.statSync (ext:deno_fs/30_fs.js:415:3)\r\n"]
[1,"    at createWalkEntrySync (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2163:22)\r\n"]
[1,"    at walkSync (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2283:11)\r\n"]
[1,"    at walkSync.next (<anonymous>)\r\n"]
[1,"    at walkSync (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2322:14)\r\n"]
[1,"    at walkSync.next (<anonymous>)\r\n"]
[1,"    at advanceMatch (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2409:16)\r\n"]
[1,"    at advanceMatch.next (<anonymous>)\r\n"]
[1,"    at expandGlobSync (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2423:18)\r\n"]
[1,"    at expandGlobSync.next (<anonymous>)\r\n"]
[1,"\u001B[39m"]
[1,"\u001B[1m\u001B[33mError\u001B[39m in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[33m!\u001B[39m Error running quarto CLI from R.\r\n"]
[1,"\u001B[1mCaused by error in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[31m✖\u001B[39m Error returned by quarto CLI.\r\n"]
[1,"  -----------------------------\r\n"]
[1,"  ERROR: NotFound: O sistema não pode encontrar o arquivo especificado. (os\r\n"]
[1,"  error 2): stat\r\n"]
[1,"  'C:\\Users\\m_tai\\Documents\\repos\\prob_inf\\.Rproj.user\\17CA65A4\\pcs'\r\n"]
[1,"  \r\n"]
[1,"  Stack trace:\r\n"]
[1,"  at Object.statSync (ext:deno_fs/30_fs.js:415:3)\r\n"]
[1,"  at createWalkEntrySync\r\n"]
[1,"  (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2163:22)\r\n"]
[1,"  at walkSync\r\n"]
[1,"  (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2283:11)\r\n"]
[1,"  at walkSync.next (<anonymous>)\r\n"]
[1,"  at walkSync\r\n"]
[1,"  (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2322:14)\r\n"]
[1,"  at walkSync.next (<anonymous>)\r\n"]
[1,"  at advanceMatch\r\n"]
[1,"  (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2409:16)\r\n"]
[1,"  at advanceMatch.next (<anonymous>)\r\n"]
[1,"  at expandGlobSync\r\n"]
[1,"  (file:///C:/Users/m_tai/AppData/Local/Programs/Quarto/bin/quarto.js:2423:18)\r\n"]
[1,"  at expandGlobSync.next (<anonymous>)\r\n"]
[1,"  \r\n"]
[1,"\u001B[1mCaused by error:\u001B[22m\r\n"]
[1,"\u001B[33m!\u001B[39m System command 'quarto.exe' failed\r\n"]
[1,"Backtrace:\r\n"]
[1,"\u001B[90m     \u001B[39m▆\r\n"]
[1,"\u001B[90m  1. \u001B[39m├─.rs.sourceWithProgress(...)\r\n"]
[1,"\u001B[90m  2. \u001B[39m│ └─\u001B[1mbase\u001B[22m::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  3. \u001B[39m│   └─base::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  4. \u001B[39m├─\u001B[1m\u001B[94mquarto::quarto_render(\u001B[39m\u001B[22m\u001B[1m\u001B[94m)\u001B[39m\u001B[22m\r\n"]
[1,"\u001B[90m  5. \u001B[39m│ └─quarto:::quarto_run(args, echo = TRUE, quarto_bin = quarto_bin)\r\n"]
[1,"\u001B[90m  6. \u001B[39m│   ├─\u001B[1mbase\u001B[22m::withCallingHandlers(...)\r\n"]
[1,"\u001B[90m  7. \u001B[39m│   └─\u001B[1mprocessx\u001B[22m::run(...)\r\n"]
[1,"\u001B[90m  8. \u001B[39m│     └─throw(...)\r\n"]
[1,"\u001B[90m  9. \u001B[39m│       └─\u001B[1mbase\u001B[22m::signalCondition(cond)\r\n"]
[1,"\u001B[90m 10. \u001B[39m└─\u001B[1mquarto\u001B[22m (local) `<fn>`(`<systm___>`)\r\n"]
[1,"\u001B[90m 11. \u001B[39m  └─quarto:::wrap_quarto_error(e, args, .call = .call)\r\n"]
[1,"\u001B[90m 12. \u001B[39m    └─\u001B[1mcli\u001B[22m::cli_abort(msg, call = .call, parent = cnd, )\r\n"]
[1,"\u001B[90m 13. \u001B[39m      └─\u001B[1mrlang\u001B[22m::abort(...)\r\n"]
[2,"Execução interrompida\r\n"]
